name: Max Contributions

on:
  push:  # Runs the workflow whenever a commit is pushed
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git Identity  # NEW STEP
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "rohanbhatotiya@gmail.com"

      - name: Make Multiple Commits
        run: |
          for i in {1..5}
          do
            echo "Commit $i on $(date)" >> log.txt
            git add log.txt
            git commit -m "Automated commit $i"
          done

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main --rebase  # Prevent conflicts
          git push origin main --force  # Force updates
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/rohanbhatotiya/automation.git
